"""create project memory schema

Revision ID: 8c211c5dcd45
Revises: 
Create Date: 2026-08-11 18:56:43.467441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c211c5dcd45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_project_id'), ['project_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('updated_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('completed_in_meeting_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['completed_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['created_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_in_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_status'), ['status'], unique=False)

    op.create_table('blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('updated_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('resolved_in_meeting_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['updated_in_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_status'), ['status'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_in_meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_project_id'), ['project_id'], unique=False)

    op.create_table('history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_events_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_project_id'), ['project_id'], unique=False)

    op.create_table('project_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('progress_summary', sa.Text(), nullable=False),
    sa.Column('completed_items', sa.JSON(), nullable=False),
    sa.Column('in_progress_items', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_in_meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_in_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('updated_in_meeting_id', sa.Integer(), nullable=False),
    sa.Column('resolved_in_meeting_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_in_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['updated_in_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_status'))
        batch_op.drop_index(batch_op.f('ix_risks_project_id'))

    op.drop_table('risks')
    op.drop_table('project_states')
    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_history_events_meeting_id'))

    op.drop_table('history_events')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_project_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockers_status'))
        batch_op.drop_index(batch_op.f('ix_blockers_project_id'))

    op.drop_table('blockers')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_status'))
        batch_op.drop_index(batch_op.f('ix_action_items_project_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_project_id'))

    op.drop_table('meetings')
    op.drop_table('projects')
    # ### end Alembic commands ###
